{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "core.service.name" $context }}
  labels: {{ include "core.general.labels" $context | nindent 4 }}
spec:
  {{- with $context.ports }}
  ports:
  {{- range $portName, $portConfig := . }}
  - name: {{ $portName }}
    protocol: TCP
    port: {{ $portConfig.port }}
    targetPort: {{ $portName }}
  {{- end }}
  {{- end }}
  selector: {{ include "core.general.selectorLabels" $context | nindent 4 }}
