{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "core.service.name" $context }}
  labels: {{ include "core.general.labels" $context | nindent 4 }}
spec:
  ports:
  - name: {{ $context.portName | default "http" }}
    protocol: TCP
    port: {{ $context.port }}
    targetPort: {{ $context.portName | default "http" }}
  selector: {{ include "core.general.selectorLabels" $context | nindent 4 }}
