name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Lint chart
        run: helm lint .

  test-single:
    name: Template / single
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Build dependencies
        run: helm dependency build
        working-directory: tests/single
      - name: Template
        run: |
          helm template core-test-single . \
            -f common.values.yaml \
            -f prod.values.yaml
        working-directory: tests/single

  test-umbrella:
    name: Template / umbrella
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Build dependencies
        run: helm dependency build
        working-directory: tests/umbrella
      - name: Template
        run: |
          helm template core-test-umbrella . \
            -f common.values.yaml \
            -f prod.values.yaml
        working-directory: tests/umbrella
