name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Lint chart
        run: helm lint .

  test-single:
    name: Template / single
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Template
        run: >-
          helm template core-test-single .
          --dependency-update
          -f common.values.yaml
          -f prod.values.yaml
        working-directory: test-charts/single

  test-umbrella:
    name: Template / umbrella
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Template
        run: >-
          helm template core-test-umbrella .
          --dependency-update
          -f common.values.yaml
          -f prod.values.yaml
        working-directory: test-charts/umbrella

  unit-tests:
    name: Unit Tests / single
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false
      - name: Build dependencies
        run: helm dependency build
        working-directory: test-charts/single
      - name: Run unit tests
        run: helm unittest -f 'unit-tests/*_test.yaml' .
        working-directory: test-charts/single
