name: Test Helm Core

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_call:

jobs:
  unit-tests-single:
    name: Unit Tests / single
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false
      - name: Build dependencies
        run: helm dependency build
        working-directory: test-charts/single
      - name: Run unit tests
        run: helm unittest -f 'unit-tests/*_test.yaml' .
        working-directory: test-charts/single

  unit-tests-umbrella:
    name: Unit Tests / umbrella
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false
      - name: Build dependencies
        run: helm dependency build
        working-directory: test-charts/umbrella
      - name: Run unit tests
        run: helm unittest -f 'unit-tests/*_test.yaml' .
        working-directory: test-charts/umbrella
